<?php
/**
 * @var umicms\project\module\blog\model\object\BlogPost $blogPost
 */
?>
<div class="blog-post">
    <h1><?= $blogPost->displayName ?></h1>
    <p class="blog-post-meta">
        <?php if ($blogPost->publishTime) : ?>
        <time datetime="<?= $blogPost->publishTime->format('c')?>">
            <?= $blogPost->publishTime->format('d.m.Y | H:i')?>
        </time>
        <?php endif; ?>
        <?php if ($blogPost->author) : ?><?=$this->translate('Author')?>: <a href="<?=$blogPost->author->getPageUrl()?>"><?=$blogPost->author->displayName?></a><?php endif; ?>
        <?=$this->widget('blog.reject.edit.editLink', ['blogPost' => $blogPost, 'template' => 'editPostLink'])?>
    </p>

    <?= $blogPost->announcement ?>

    <a href="<?= $blogPost->getPageUrl() ?>"><?=$this->translate('Read more')?></a>
    <div class="btn-toolbar">
        <?=$this->widget('blog.reject.sendToModeration', ['blogPost' => $blogPost, 'template' => 'sendToModerationForm'])?>
    </div>
</div>