<?php
/**
 * @var umicms\project\module\blog\api\object\BlogCategory $category
 * @var umi\orm\selector\ISelector $categories
 */
?>

<?php if ($categories->getTotal()) :?>

    <ul>
        <?php foreach ($categories as $category) : ?>
            <li>
                <?= $this->widget('blog.category.view', ['category' => $category, 'template' => 'shortView']); ?>
                <?= $this->widget('blog.category.rss', ['category' => $category, 'template' => 'rssLink']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>