<?php
/**
 * @var umicms\project\module\blog\api\object\BlogCategory $page
 */
?>
<h1><?= $page->h1 ?></h1>
<?= $page->contents ?>

<?= $this->widget('blog.category.list', ['parentCategory' => $page, 'template' => 'list']); ?>
<?= $this->widget('blog.category.postList', ['categories' => [$page], 'template' => 'postList']); ?>

<h1>Создать пост</h1>
<?= $this->widget('blog.post.addPost', ['blogCategory' => $page, 'template' => 'addPostForm']); ?>