<?php
/**
 * @var umicms\project\module\structure\model\object\SystemPage $page
 * @var umi\form\FormEntityView $form
 * @var umicms\project\module\dispatches\model\object\Subscriber $subscriber
 * @var bool $contains
 */
?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->getHeader()?></h2>
    <?=$page->contents?>
        <?= $errors = isset($errors) ? $errors : null ?>
        <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>
</div>