<?php
/**
* @var umicms\project\module\structure\api\object\SystemPage $page
*/
?>
<h1><?= $page->h1 ?></h1>
<?= $page->contents ?>

<?= $this->widget('blog.post.rss', ['template' => 'rssLink']); ?>
<h2>Категории</h2>
<?= $this->widget('blog.category.list', ['template' => 'list']) ?>
<h2>Облако тэгов</h2>
<?= $this->widget('blog.tag.cloud', ['template' => 'cloud']) ?>
<h2>Тэги</h2>
<?= $this->widget('blog.tag.list', ['template' => 'list']) ?>
<h2>Авторы</h2>
<?= $this->widget('blog.author.list', ['template' => 'list']) ?>
<h2>Все посты</h2>
<?= $this->widget('blog.post.list', ['template' => 'list']) ?>