<?=$this->render('partial/authorization.phtml') ?>

<div class="sidebar-module sidebar-module-inset">
    <h4><?=$this->translate('RSS ленты')?></h4>
    <p><?=$this->translate('Новости')?>: <?=$this->widget('news.item.rss', ['template' => 'rssLink'])?></p>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Рубрики')?></h4>
    <?=$this->widget('news.rubric.list', ['template' => 'listShort'])?>
    <?=$this->widget('news.rubric.tree', ['template' => 'tree'])?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Сюжеты')?></h4>
    <?=$this->widget('news.subject.list', ['template' => 'listShort'])?>
</div>

<?=$this->widget('structure.infoblock.view', ['template' => 'facebook'])?>
<?=$this->widget('structure.infoblock.view', ['template' => 'vk'])?>