<?=$this->render('partial/authorization.phtml') ?>

<div class="sidebar-module sidebar-module-inset">
    <h4><?=$this->translate('RSSFeed')?></h4>
    <p><?=$this->translate('News')?>: <?=$this->widget('news.item.rssLink', ['template' => 'rssLink'])?></p>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Rubrics')?></h4>
    <?=$this->widget('news.rubric.tree')?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Subjects')?></h4>
    <?=$this->widget('news.subject.list', ['template' => 'listShort'])?>
</div>

<?=$this->widget('structure.infoblock.view', ['template' => 'socialGroup', 'infoBlock' => 'commonInfoBlock'])?>