<div class="sidebar-module sidebar-module-inset">
    <h4><?=$this->translate('RSS ленты')?></h4>
    <p><?=$this->translate('Новости')?>: <?=$this->widget('news.item.rss', ['template' => 'rssLink'])?></p>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Рубрики')?></h4>
    <?=$this->widget('news.rubric.list', ['template' => 'listShort'])?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Сюжеты')?></h4>
    <?=$this->widget('news.subject.list', ['template' => 'listShort'])?>
</div>
