
<?=$this->render('partial/authorization.phtml') ?>

<div class="sidebar-module sidebar-module-inset">
    <h4><?=$this->translate('RSS ленты')?></h4>
    <p><?=$this->translate('Блоги')?>: <?=$this->widget('blog.post.rss', ['template' => 'rssLink'])?></p>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Категории')?></h4>
    <?=$this->widget('blog.category.list', ['template' => 'listShort'])?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Облако тэгов')?></h4>
    <?=$this->widget('blog.tag.cloud', ['template' => 'cloud'])?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Авторы')?></h4>
    <?=$this->widget('blog.author.list', ['template' => 'listShort'])?>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Черновики')?></h4>
    <ol class="list-unstyled">
        <li><?=$this->translate('Черновики автора')?>: <?=$this->widget('blog.draft.ownListUrl', ['template' => 'draftLinkAuthor'])?></li>
    </ol>
</div>
<div class="sidebar-module">
    <h4><?=$this->translate('Модерирование')?></h4>
    <ol class="list-unstyled">
        <li><?=$this->translate('Очередь на модерацию')?>:</li>
    </ol>
</div>