<?php
/**
 * @var umicms\pagination\CmsPaginator $paginator
 */

?>

<?php if ($paginator->getPagesCount()) : ?>
    <ul class="pagination">
        <?php if ($paginator->getPreviousPage()) : ?>
            <li><a href="<?= $paginator->getPreviousPageUrl() ?>"><?=$this->translate('Previous')?></a></li>
        <?php endif; ?>
        <?php foreach ($paginator->getRangeUrls() as $page => $link) : ?>

            <?php if ($page != $paginator->getCurrentPage()) : ?>
                <li><a href="<?= $link ?>"><?= $page ?></a></li>
            <?php else : ?>
                <li class="active"><span><?= $page ?></span></li>
            <?php endif; ?>

        <?php endforeach; ?>
        <?php if ($paginator->getNextPage()) : ?>
            <li><a href="<?= $paginator->getNextPageUrl() ?>"><?=$this->translate('Next')?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>