<?php
/**
 * @var umicms\pagination\CmsPaginator $paginator
 */

?>

<?php if ($paginator->pagesCount) : ?>
    <ul class="pagination">
        <?php if ($paginator->previousPage) : ?>
            <li><a href="<?= $paginator->previousPageUrl ?>"><?=$this->translate('Previous')?></a></li>
        <?php endif; ?>
        <?php foreach ($paginator->rangeUrls as $page => $link) : ?>

            <?php if ($page != $paginator->currentPage) : ?>
                <li><a href="<?= $link ?>"><?= $page ?></a></li>
            <?php else : ?>
                <li class="active"><span><?= $page ?></span></li>
            <?php endif; ?>

        <?php endforeach; ?>
        <?php if ($paginator->nextPage) : ?>
            <li><a href="<?= $paginator->nextPageUrl ?>"><?=$this->translate('Next')?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>