<?php
/**
 * @var umicms\project\module\blog\model\object\BlogCategory $category
 * @var umicms\orm\selector\CmsSelector $list
 */
?>
<?php if ($list->getTotal()) : ?>
    <ol class="list-unstyled">
        <? foreach ($list as $category) : ?>
            <li>
                <?=$this->widget('blog.category.view', ['category' => $category, 'template' => 'listShortView'])?>
            </li>
        <?php endforeach; ?>
    </ol>
<? endif; ?>