<?php
/**
 * @var \umicms\orm\selector\CmsSelector $list
 * @var \umicms\project\module\news\api\object\NewsRubric $rubric
 */
?>
<?php if ($list->getTotal()) : ?>
    <ul class="list-unstyled">
        <?php foreach ($list as $rubric) : ?>
            <li>
                <?=$this->widget('news.rubric.view', ['rubric' => $rubric, 'template' => 'listShortView'])?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>