<?php
/**
 * @var umicms\project\module\news\model\object\NewsRubric $rubric
 * @var umicms\orm\selector\CmsSelector $list
 */
?>

<?php if ($list->getTotal()) :?>
    <ul  class="list-unstyled">
        <?php foreach ($list as $rubric) : ?>
            <li>
                <?= $this->widget('news.rubric.view', ['rubric' => $rubric, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>