<?php
use umicms\project\module\structure\model\object\StructureElement;

/** @var StructureElement $page */
/** @var array $menu */

?>
<?php if (count($menu)) : ?>
    <ul class="nav navbar-nav">
    <?php foreach ($menu as $pageInfo) : ?>
        <li class="<?= $pageInfo['active'] ? 'active' : '' ?>">
            <a href="<?= $pageInfo['page']->getPageUrl() ?>"><?= $pageInfo['page']->displayName ?></a>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>