<?php
use umicms\project\module\structure\api\object\StructureElement;

/** @var StructureElement $page */
/** @var array $menu */

?>
<?php if (count($menu)) : ?>
    <nav class="blog-nav">
        <?php foreach ($menu as $pageInfo) : ?>
            <a class="blog-nav-item <?= $pageInfo['active'] ? 'active' : '' ?>"
               href="<?= $pageInfo['page']->getPageUrl() ?>">
                <?= $pageInfo['page']->displayName ?>
            </a>
        <?php endforeach; ?>
    </nav>
<?php endif; ?>