<?php
/**
 * @var \umicms\orm\selector\CmsSelector $comments
 * @var umicms\project\module\blog\api\object\BlogComment $blogComment
 */
?>
<?php if ($comments->getTotal()) :?>
    <ul>
        <?php foreach ($comments as $blogComment) : ?>
            <li>
                <?= $this->widget('blog.comment.view', ['blogComment' => $blogComment, 'template' => 'view']); ?>
                <?= $this->widget('blog.comment.add', ['blogPost' => $blogComment->post, 'blogComment' => $blogComment, 'template' => 'addComment']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>