<?php
/**
 * @var \umicms\orm\selector\CmsSelector $comments
 * @var umicms\project\module\blog\api\object\BlogComment $blogComment
 */
?>
<?php if ($comments->getTotal()) {
    $level = 0;
    foreach ($comments as $blogComment) {
        if ($blogComment->level == $level) {
            echo "</li>\n";
        } else {
            if ($blogComment->level > $level) {
                echo "<ul>\n";
            } else {
                echo "</li>\n";

                for ($i = $level - $blogComment->level; $i; $i--) {
                    echo "</ul>\n</li>\n";

                }
            }
        }
        echo "<li>";
        echo $this->widget('blog.comment.view', ['blogComment' => $blogComment, 'template' => 'view']);
        //echo $this->widget('blog.comment.addComment', ['blogPost' => $blogComment->post, 'blogComment' => $blogComment, 'template' => 'addComment']);
        $level = $blogComment->level;
    }
    for ($i = $level; $i; $i--) {
        echo "</li>\n</ul>\n";
    }
}