<?php
/**
 * @var umicms\project\module\blog\api\object\BlogComment $blogComment
 */
?>
<div class="media-body">
<h1><?= $blogComment->displayName ?></h1>
<?php if ($blogComment->publishTime) : ?>
<time datetime="<?= $blogComment->publishTime->format('c') ?>">
    <?= $blogComment->publishTime->format('d.m.Y | H:i') ?>
</time>
<?php endif; ?>
    <?= $this->widget('blog.comment.publish', ['blogComment' => $blogComment, 'template' => 'publishForm']); ?>
    <?= $this->widget('blog.comment.reject', ['blogComment' => $blogComment, 'template' => 'rejectForm']); ?>
    <?= $blogComment->contents ?>
</div>