<?php
/**
 * @var umicms\project\module\blog\model\object\BlogComment $blogComment
 */

?>
<div class="media-body">
    <h1><?= $blogComment->displayName ?></h1>
    <?php if ($blogComment->publishTime) : ?>
    <time datetime="<?= $blogComment->publishTime->format('c') ?>">
        <?= $blogComment->publishTime->format('d.m.Y | H:i') ?>
    </time>
    <?php endif; ?>
    <?= $blogComment->contents ?>

    <?php if ($blogComment->publishStatus == $blogComment::COMMENT_STATUS_NEED_MODERATE) : ?>
    <div class="btn-toolbar">
        <?= $this->widget('blog.comment.publish', ['blogComment' => $blogComment, 'template' => 'publishForm']); ?>
        <?= $this->widget('blog.comment.reject', ['blogComment' => $blogComment, 'template' => 'rejectForm']); ?>
    </div>
    <?php endif; ?>
</div>