<?php
/**
 * @var umicms\project\module\blog\api\object\BlogCategory $category
 * @var umicms\orm\selector\CmsSelector $list
 */
?>

<?php if ($list->getTotal()) :?>
    <ul>
        <?php foreach ($list as $category) : ?>
            <li>
                <?= $this->widget('blog.category.view', ['category' => $category, 'template' => 'shortView']); ?>
                <?= $this->widget('blog.category.rss', ['category' => $category, 'template' => 'rssLink']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>