<?php
/**
 * @var umicms\project\module\blog\module\object\BlogCategory $page
 */
?>

<?=$this->render('breadcrumbs.phtml', $scope) ?>

<h1><?= $page->displayName ?></h1>
<?= $this->widget('blog.post.add.addLink', ['blogCategory' => $page, 'template' => 'addPostLink']); ?>
<?= $page->contents ?>

<?= $this->widget('blog.category.list', ['parentCategory' => $page, 'template' => 'list']); ?>
<?= $this->widget('blog.category.postList', ['categories' => [$page], 'template' => 'postList']); ?>
