<?php
/**
 * @var array $elementInfo
 * @var \umi\form\element\IFormInput $element
 */
?>
<?php $element = $elementInfo['element']?>

<?php if ($element->getInputType() != 'hidden') : ?>
    <div class="form-group">
        <label><?= $elementInfo['label'] ?></label>
        <input class="form-control" <?= $elementInfo['attributes'] ?> />
    </div>
<?php else : ?>
    <input <?= $elementInfo['attributes'] ?> />
<?php endif; ?>