<?php
/**
 * @var \umi\form\element\IFormInput $input
 */
$attributes = array_merge(
    $input->getAttributes(),
    [
        'type' => $input->getInputType(),
        'name' => $input->getElementName(),
        'value' => $input->getValue()
    ]
);
echo '<div class="form-group"><label>' . (($input->getInputType() != 'hidden') ? $input->getName() : '') . '</label><input class="form-control" ' . buildAttributes($attributes) .' /></div>';