<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>

<div class="form-group">
    <label><?= $element->label ?></label>

    <?php if (!$element->valid) : ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($element->errors as $message) : ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <select class="form-control" <?= $element->attributes ?> >

        <?php foreach ($element->choices as $choice) : ?>
            <option <?= $choice['attributes'] ?> ><?= $choice['label'] ?></option>
        <?php endforeach; ?>

    </select>
</div>
