<?php
/** @var \Exception $error */
/** @var int $code */
?>

<?php if ($code == 404):?>
    <h1>A 404 error occurred</h1>

    <h2><?= $error->getMessage() ?></h2>

<?php elseif($code == 403): ?>
    <h1>Access denied</h1>

    <h2><?= $error->getMessage() ?></h2>
<?php else: ?>

    <div>
        <h1>An error occurred</h1>

        <h2><?= $error->getMessage(); ?></h2>

        <hr/>
        <h2>Additional information:</h2>

        <h3><?= get_class($error); ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $error->getFile() ?>:<?= $error->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $error->getMessage() ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $error->getTraceAsString() ?></pre>
            </dd>
        </dl>
        <?php
        $error = $error->getPrevious();

        if ($error) :
            ?>
            <hr/>
            <h2>Previous exceptions:</h2>
            <ul>
                <?php while ($error) : ?>
                    <li>
                        <h3><?= get_class($error); ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre><?= $error->getFile() ?>:<?= $error->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre><?= $error->getMessage(); ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre><?= $error->getTraceAsString() ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $error = $error->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>
    </div>

<?php endif;?>