<!DOCTYPE HTML>
<html data-foundation>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>UMI.CMS</title>
        <link rel="stylesheet" type="text/css" href="/resources/deploy/styles.css">
        <script>
            // Ember settings
            ENV = {
                ENABLE_ALL_FEATURES: true
            };
            window.UmiSettings = {
                "baseURL": '<?= $baseUrl ?>',
                "baseApiURL": '<?= $baseApiUrl ?>',
                "baseSettingsURL": '<?= $baseSettingsUrl ?>',
                "baseSiteURL": '<?= $baseSiteUrl ?>',
                "authUrl": '<?= $authUrl ?>'
            }
        </script>
    </head>
    <body id="body" style="background: #D6E0E9; background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0iIzRDNjE3RCI+DQogIDxwYXRoIG9wYWNpdHk9Ii4yNSIgZD0iTTE2IDAgQTE2IDE2IDAgMCAwIDE2IDMyIEExNiAxNiAwIDAgMCAxNiAwIE0xNiA0IEExMiAxMiAwIDAgMSAxNiAyOCBBMTIgMTIgMCAwIDEgMTYgNCIvPg0KICA8cGF0aCBkPSJNMTYgMCBBMTYgMTYgMCAwIDEgMzIgMTYgTDI4IDE2IEExMiAxMiAwIDAgMCAxNiA0eiI+DQogICAgPGFuaW1hdGVUcmFuc2Zvcm0gYXR0cmlidXRlTmFtZT0idHJhbnNmb3JtIiB0eXBlPSJyb3RhdGUiIGZyb209IjAgMTYgMTYiIHRvPSIzNjAgMTYgMTYiIGR1cj0iMC44cyIgcmVwZWF0Q291bnQ9ImluZGVmaW5pdGUiIC8+DQogIDwvcGF0aD4NCjwvc3ZnPg==); background-repeat: no-repeat; background-position: center center; background-size: 10%">
        <script data-main="/resources/main" src="/resources/libs/requirejs/require.js"></script>

        <noscript>
            <div class="auth-layout">
                <div class="bubbles"></div>
                <div class="bubbles-front"></div>
                <div class="row vertical-center">
                    <div class="large-centered columns large-3">
                        <p class="text-center">
                            <img src="/resources/deploy/img/auth-logo.png"/>
                        </p>
                        <div>
                            <div class="panel pretty radius shake-it">
                                <p class="text-center">Для работы с UMI.CMS необходимо <a target="_blank" href="https://support.google.com/adsense/answer/12654?hl=ru">включить Javascript</a> в вашем браузере.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="auth-mask"></div>
        </noscript>
    </body>
</html>