<?php
/**
 * @var Fragmenter $fragmenter
 */
use umicms\project\module\search\highlight\Fragment;
use umicms\project\module\search\highlight\Fragmenter;

?>
<div class="mod-search mod-search-result-list">
    <?
    /** @var $fragment Fragment */
    foreach ($fragmenter as $fragment) {
    ?>
    <span class="mod-search-fragment">
        <span class="before">...<?= implode(' ', $fragment->getEdgeLeft()); ?></span>
        <span class="keyword"><?= $this->widget('highlight', $fragment->getCenter()) ?></span>
        <span class="after"><?= implode(' ', $fragment->getEdgeRight()); ?>...</span>
    </span>
</div>
