<?php
/**
 * @var \umicms\orm\selector\CmsSelector $list
 * @var umicms\project\module\blog\model\object\BlogAuthor $blogAuthor
 */
?>
<?php if ($list->getTotal()) : ?>
    <ul>
        <?php foreach ($list as $blogAuthor) : ?>
            <li>
                <?= $this->widget(
                    'blog.author.view.author',
                    ['blogAuthor' => $blogAuthor, 'template' => 'shortView']
                ); ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>