<?php
/**
 * @var \umicms\hmvc\view\CmsTreeView[] $tree
 * @var \umicms\hmvc\view\CmsTreeNode $node
 */
?>
<?php if (count($tree) > 0) : ?>
    <ul>
        <?php foreach ($tree as $node) : ?>
            <li>
                <?= $this->widget('blog.comment.view', ['blogComment' => $node->item, 'template' => 'view']); ?>
                <?= $this->widget('blog.comment.add.addForm', ['blogPost' => $node->item->post, 'blogComment' => $node->item, 'template' => 'addSubComment']); ?>
                <?= $this->render('tree.phtml', ['tree' => $node->children]); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>