<?php
/**
 * @var umicms\project\module\blog\model\object\BlogComment $blogComment
 */
use umicms\project\module\blog\model\object\BlogAuthor;
use umicms\project\module\blog\model\object\CommentStatus;

?>
<div class="media-body">
    <?php if ($blogComment->status->guid == CommentStatus::GUID_UNPUBLISHED) : ?>
        <?= $this->translate('Comment has been unpublished.') ?>
    <?php else : ?>
        <h1><?= $blogComment->displayName ?></h1>
        <p class="blog-post-meta">
            <?php if ($blogComment->publishTime) : ?>
                <time datetime="<?= $blogComment->publishTime->format('c') ?>">
                    <?= $blogComment->publishTime->format('d.m.Y | H:i') ?>
                </time>
            <?php endif; ?>
            <?php if ($blogComment->author instanceof BlogAuthor) : ?>
                <?=$this->translate('Author')?>: <a href="<?=$blogComment->author->getPageUrl()?>"><?=$blogComment->author->displayName?></a>
            <?php endif; ?>
        </p>

        <?= $blogComment->contents ?>

        <?php if ($blogComment->status->guid == CommentStatus::GUID_NEED_MODERATION) : ?>
            <div class="btn-toolbar">
                <?= $this->widget('blog.comment.publishForm', ['blogComment' => $blogComment, 'template' => 'publishForm']); ?>
                <?= $this->widget('blog.comment.rejectForm', ['blogComment' => $blogComment, 'template' => 'rejectForm']); ?>
            </div>
        <?php endif; ?>

        <?php if ($blogComment->status->guid == CommentStatus::GUID_PUBLISHED) : ?>
            <div class="btn-toolbar">
                <?= $this->widget('blog.comment.unpublishForm', ['blogComment' => $blogComment, 'template' => 'unpublishForm']); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>