<?php
/**
 * @var \umicms\hmvc\view\CmsTreeView[] $tree
 * @var \umicms\hmvc\view\CmsTreeNode $node
 */
?>
<?if (count($tree) > 0) : ?>
    <ul class="bottomMenu">
        <?foreach ($tree as $node) : ?>
            <?$ac = $node->getArrayCopy();?>
            <li <?if($node->active):?>class="active"<?endif?>>
                <?if($node->current):?>
                    <?=$node->item->displayName?>
                <?else:?>
                <a href="<?= $node->item->getItemUrl() ?: $this->anchor() ?>"
                    <?=$node->item->getItemType() == 'externalItem' ? 'target="blank"' : ''; ?> >
                    <?=$node->item->displayName?>
                </a>
                <?endif?>
                <?= $this->render('customMenu.phtml', ['tree' => $node->children]); ?>
            </li>
        <?endforeach;?>
    </ul>
<?endif;?>