<?php
/**
 * @var \umicms\hmvc\view\CmsTreeView[] $tree
 * @var \umicms\hmvc\view\CmsTreeNode $node
 */
?>
<?php if (count($tree) > 0) : ?>
    <ul class="bottomMenu">
        <?php foreach ($tree as $node) : ?>
            <li <?php if($node->active):?>class="active"<?php endif?>>
                <?php if($node->current):?>
                    <?=$node->item->displayName?>
                <?php else:?>
                    <a href="<?= $node->item->getItemUrl() ?: $this->anchor() ?>"
                        <?=$node->item->getItemType() == 'externalItem' ? 'target="blank"' : ''; ?> >
                        <?=$node->item->displayName?>
                    </a>
                <?php endif?>
                <?= $this->render('customMenu.phtml', ['tree' => $node->children]); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif;?>