<?php
/**
 * @var umicms\project\module\structure\model\object\SystemPage $page
 * @var umi\form\IForm $form
 * @var bool $authenticated
 */
?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->displayName?></h2>
    <?=$page->contents?>

    <?php if ($authenticated) : ?>
        <?= $this->translate("You are already logged in") ?>.
        <p>
            <?= $this->widget('users.profile.link', ['template' => 'link']); ?>
        </p>
        <?= $this->widget('users.authorization.logoutForm', ['template' => 'logoutForm']); ?>
    <?php else : ?>
        <?php $errors = isset($errors) ? $errors : null ?>
        <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>
    <?php endif; ?>


</div>