<?php
/**
 * @var umicms\project\module\news\api\object\NewsSubject $subject
 * @var umi\orm\selector\ISelector $subjects
 */
?>

<?php if ($subjects->getTotal()) :?>

    <ul>
        <?php foreach ($subjects as $subject) : ?>
            <li>
                <?= $this->widget('news.subject.view', ['guid' => $subject->guid, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>