<?php
/**
 * @var umi\orm\selector\ISelector $tags
 * @var umicms\project\module\blog\api\object\BlogTag $blogTag
 */
?>
<?php if ($tags->getTotal()) :?>

    <ul>
        <?php foreach ($tags as $blogTag) : ?>
            <li>
                <?= $this->widget('blog.tag.view', ['blogTag' => $blogTag, 'template' => 'shortView']); ?>
                <?= $this->widget('blog.tag.rss', ['blogTag' => $blogTag, 'template' => 'rssLink']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>