<?php
/**
 * @var Fragmenter $fragmenter
 * @var string $query
 */
use umicms\project\module\search\highlight\Fragment;
use umicms\project\module\search\highlight\Fragmenter;

?>
<div class="mod-search mod-search-result-list">
    <?
    /** @var $fragment Fragment */
    foreach ($fragmenter as $fragment) {
        $textBefore = implode(' ', $fragment->getEdgeLeft());
        $textAfter = implode(' ', $fragment->getEdgeRight());
    ?>
    <span class="mod-search-fragment">
        <span class="before">...<?= $this->widget('search.highlight', ['text' => $textBefore,'query' => $query,]) ?></span>
        <span class="keyword"><?= $this->widget('search.highlight', ['text' => $fragment->getCenter(),'query' => $query,]) ?></span>
        <span class="after"><?= $this->widget('search.highlight', ['text' => $textAfter,'query' => $query,]) ?>...</span>
    </span>
    <?}?>
</div>
