<?php
/**
 * @var umicms\project\module\search\model\highlight\Fragmenter $fragmenter
 * @var umicms\project\module\search\model\highlight\Fragment $fragment
 * @var string $query
 */
?>

<div>
    <?php foreach ($fragmenter as $fragment) : ?>

    <span>
        <span class="before">...<?= $this->widget('search.highlight', ['text' => implode(' ', $fragment->getEdgeLeft()),'query' => $query,]) ?></span>
        <span class="keyword"><?= $this->widget('search.highlight', ['text' => $fragment->getCenter(),'query' => $query,]) ?></span>
        <span class="after"><?= $this->widget('search.highlight', ['text' => implode(' ', $fragment->getEdgeRight()),'query' => $query,]) ?>...</span>
    </span>
    <?php endforeach; ?>
</div>
