<?php
/**
 * @var umicms\project\module\search\model\highlight\Fragmenter $fragmenter
 * @var umicms\project\module\search\model\highlight\Fragment $fragment
 * @var string $query
 */
?>

<div class="mod-search mod-search-result-list">
    <?
    foreach ($fragmenter as $fragment) {
        $textBefore = implode(' ', $fragment->getEdgeLeft());
        $textAfter = implode(' ', $fragment->getEdgeRight());
    ?>

    <span class="mod-search-fragment">
        <span class="before">...<?= $this->widget('search.highlight', ['text' => $textBefore,'query' => $query,]) ?></span>
        <span class="keyword"><?= $this->widget('search.highlight', ['text' => $fragment->getCenter(),'query' => $query,]) ?></span>
        <span class="after"><?= $this->widget('search.highlight', ['text' => $textAfter,'query' => $query,]) ?>...</span>
    </span>
    <?}?>
</div>
