<?php
/**
 * @var umicms\project\module\surveys\model\object\Survey $page
 * @var umi\form\FormEntityView $form
 * @var bool $voted
 */
?>

<?=$this->render('breadcrumbs.phtml', $scope) ?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->getHeader()?></h2>
    <?=$page->contents?>

    <?php if ($voted) : ?>
        <p><?= $this->translate("You have already voted") ?>.</p>
    <?php else : ?>
        <?php $errors = isset($errors) ? $errors : null ?>
        <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>
    <?php endif; ?>

</div>