<?php
/**
 * @var umicms\project\module\blog\model\object\BlogPost $blogPost
 */
use umicms\project\module\blog\model\object\BlogAuthor;
use umicms\project\module\blog\model\object\BlogPost;

?>
<div class="blog-post">
    <h1><?= $blogPost->displayName ?></h1>
    <p class="blog-post-meta">
        <?php if ($blogPost->publishTime) : ?>
        <time datetime="<?= $blogPost->publishTime->format('c')?>">
            <?= $blogPost->publishTime->format('d.m.Y | H:i')?>
        </time>
        <?php endif; ?>
        <?php if ($blogPost->author instanceof BlogAuthor) : ?>
            <?=$this->translate('Author')?>: <a href="<?=$blogPost->author->getPageUrl()?>"><?=$blogPost->author->displayName?></a>
        <?php else : ?>
            <?=$this->translate('Author')?>: <?=$blogPost->authorGuest?>
        <?php endif; ?>
        <?=$this->widget('blog.moderate.edit.editLink', ['blogPost' => $blogPost, 'template' => 'editPostLink'])?>
    </p>

    <?= $blogPost->announcement ?>

    <a href="<?= $blogPost->getPageUrl() ?>"><?=$this->translate('ReadMore')?></a>

    <div class="btn-toolbar">
        <?=$this->widget('blog.moderate.publishForm', ['blogPost' => $blogPost, 'template' => 'publishForm'])?>
        <?=$this->widget('blog.moderate.rejectForm', ['blogPost' => $blogPost, 'template' => 'rejectForm'])?>
        <?php if ($blogPost instanceof BlogPost) : ?>
            <?=$this->widget('blog.moderate.toDraftForm', ['blogPost' => $blogPost, 'template' => 'draftForm'])?>
        <?php endif; ?>
    </div>
</div>