<?php
/**
 * @var umi\form\IForm $form
 * @var array $submit
 */
?>

<?php $formInfo = $this->form($form); ?>

<?php if (isset($errors)) : ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($errors as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<form <?= $formInfo['attributes'] ?> >

    <?php foreach ($formInfo['elements'] as $elementInfo) : ?>
        <?= $this->render('form/element.phtml', ['elementInfo' => $elementInfo]); ?>
    <?php endforeach; ?>

</form>
