<?php
/**
 * @var umi\form\FormEntityView $form
 * @var umicms\project\module\blog\model\object\BlogComment $blogComment
 */

?>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#comment-<?= $blogComment->getId() ?>">
    <?= $this->translate('Add comment')  ?>
</button>
<div id="comment-<?= $blogComment->getId() ?>" class="collapse">
    <?=$this->render('form/form.phtml', ['form' => $form])?>
</div>