<?php
/**
 * @var array $pagination
 */
?>

<?php if (isset($pagination['pagesCount'])) : ?>
    <?php if (isset($pagination['pagesCount'])) : ?>
        <ul class="pagination">
            <?php if ($pagination['previousPageUrl']) : ?>
                <li><a href="<?= $pagination['previousPageUrl'] ?>"><?=$this->translate('Previous')?></a></li>
            <?php endif; ?>
            <?php foreach ($pagination['pagesRange'] as $page => $link) : ?>

                <?php if ($page != $pagination['currentPage']) : ?>
                    <li><a href="<?= $link ?>"><?= $page ?></a></li>
                <?php else : ?>
                    <li class="active"><span><?= $page ?></span></li>
                <?php endif; ?>

            <?php endforeach; ?>
            <?php if ($pagination['nextPageUrl']) : ?>
                <li><a href="<?= $pagination['nextPageUrl'] ?>"><?=$this->translate('Next')?></a></li>
            <?php endif; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>