
<footer class="blog-footer">
    <?=$this->widget('structure.menu.custom', ['menuName' => 'footer'])?>

    <?=$this->widget('structure.infoblock.view', ['template' => 'footer', 'infoBlock' => 'commonInfoBlock'])?>
    <p>
        <a href="#"><?=$this->translate('BackToTop')?></a>
    </p>
</footer>

<?=$this->widget('topBar')?>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="<?=$assetsUrl?>bootstrap/js/bootstrap.min.js"></script>
<script src="<?=$assetsUrl?>bootstrap/js/docs.min.js"></script>
