
<footer class="blog-footer">
    <?=$this->widget('structure.menu.custom', ['parentNode' => '104be372-0550-469d-9a63-f36a361139a5'])?>

    <?=$this->widget('structure.infoblock.view', ['template' => 'footer', 'infoBlock' => 'commonInfoBlock'])?>
    <p>
        <a href="<?= $this->anchor()?>"><?=$this->translate('BackToTop')?></a>
    </p>
</footer>

<?=$this->widget('topBar')?>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="bootstrap/js/docs.min.js"></script>
