<?php
/**
 * @var umicms\orm\selector\CmsSelector $list
 * @var array $pagination
 * @var umicms\project\module\news\api\object\NewsItem $newsItem
 */
?>
<?php if ($list->getTotal()) :?>

    <ul>
        <?php foreach ($list as $newsItem) : ?>
            <li>
                <?= $this->widget('news.item.view', ['newsItem' => $newsItem, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ul>

    <!--TODO: сделать общий шаблон для пагинации-->
    <?= $this->render('pagination.phtml', ['pagination' => $pagination]); ?>

<?php endif; ?>