<?php
/**
 * @var umicms\project\module\news\api\object\NewsItem $newsItem
 */
?>
<div class="blog-post">
    <h2 class="blog-post-title"><?=$newsItem->displayName?></h2>
    <p class="blog-post-meta">
        <?php if ($newsItem->date) :?>
            <time datetime="<?= $newsItem->date->format('c')?>">
                <?= $newsItem->date->format('d.m.Y | H:i')?>
            </time>
        <?php endif; ?>
        <?=$this->widget('news.subject.list', ['template' => 'listInline'])?>
    </p>

    <?= $newsItem->announcement ?>

    <a href="<?= $newsItem->getPageUrl() ?>"><?=$this->translate('Read more')?></a>
</div>