<?php
/**
 * @var umicms\project\module\news\model\object\NewsSubject $subject
 * @var umicms\orm\selector\CmsSelector $list
 */
?>

<?php if ($list->getTotal()) :?>
    <ul>
        <?php foreach ($list as $subject) : ?>
            <li>
                <?= $this->widget('news.subject.view', ['subject' => $subject, 'template' => 'shortView']); ?>
                <?= $this->widget('news.subject.rssLink', ['subject' => $subject, 'template' => 'rssLink']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>