<?php
/**
 * @var \umicms\orm\selector\CmsSelector $list
 * @var \umicms\project\module\news\api\object\NewsSubject $subject
 */
?>
<?php if ($list->getTotal()) : ?>
    <ol class="list-unstyled">
        <?php foreach ($list as $subject) : ?>
            <li>
                <?=$this->widget('news.subject.view', ['subject' => $subject, 'template' => 'shortView'])?>
                <?=$this->widget('news.subject.rssLink', ['subject' => $subject, 'template' => 'rssLink'])?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>