<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>

<?php if (!$element->valid) : ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($element->errors as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php foreach ($element->choices as $choice) : ?>
    <label><input <?= $choice['attributes'] ?> /><?= $choice['label'] ?></label>
<?php endforeach; ?>

