<?php
/**
 * @var string $activationCode
 * @var string $projectUrl
 */
?>
<p><?= $this->translate('Hello')?>,</p>
<p>
    <?= $this->translate(
        'Password reset request was received for you account {site}. Please click the link below to reset you password',
        ['site' => $projectUrl])
    ?>:
    <br/>
    <?= $this->widget('users.restoration.confirmation.link', ['template' => 'link', 'activationCode' => $activationCode]); ?>
</p>
<p>
    <?= $this->translate('Ignore this message if you did not send reset request')?>.
</p>


