<?php
/**
 * @var umicms\project\module\blog\api\object\BlogPost $blogPost
 */
?>
<div class="blog-post">
    <h1><?=$blogPost->h1?></h1>
    <p class="blog-post-meta">
        <time datetime="<?= $blogPost->publishTime->format('c')?>">
            <?= $blogPost->publishTime->format('d.m.Y | H:i')?>
        </time>
        Автор: <?php if ($blogPost->author) : ?><a href="<?=$blogPost->author->getPageUrl()?>"><?=$blogPost->author->displayName?></a><?php endif; ?>
        <?=$this->widget('blog.post.editPostLink', ['blogPost' => $blogPost, 'template' => 'editPostLink'])?>
    </p>

    <?= $blogPost->announcement ?>

    <a href="<?=$blogPost->getPageUrl()?>">Читать далее</a>
    <?=$this->widget('blog.post.unPublish', ['blogPost' => $blogPost, 'template' => 'unPublishPostForm'])?>
</div>