<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>


<?php if (!$element->isHuman) : ?>

    <div class="form-group <?= $element->attributes->name ?> <?= !$element->valid ? 'has-error' : '' ?>">
        <label for="<?= $element->attributes->id ?>"><?= $element->label ?></label>

        <?php if (!$element->valid) : ?>
            <div class="alert alert-danger">
                <ul>
                    <?php foreach ($element->errors as $message) : ?>
                        <li><?= $message ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <script type="text/javascript">
            function reloadCaptcha_<?= $element->sessionKey ?>() {
                var img = document.getElementById('<?= $element->sessionKey ?>');
                img.src = '<?= $element->url ?>?t=' + (new Date()).getTime();
            }
        </script>
        <div class="input-group">
            <span class="input-group-addon">
                <img id="<?= $element->sessionKey ?>" src="<?= $element->url ?>" alt="<?= $element->label ?>" title="<?= $element->label ?>">
                <button class="btn btn-default glyphicon glyphicon-refresh" onclick="reloadCaptcha_<?= $element->sessionKey ?>();return false;"></button>
            </span>
            <input type="text" class="form-control input-lg" <?= $element->attributes ?>>
        </div>

    </div>

<?php endif; ?>
