<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>

<div class="form-group <?= $element->attributes->name ?> <?= $element->valid ? 'hidden' : 'has-error' ?>">
    <?php if (!$element->valid) : ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($element->errors as $message) : ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <input <?= $element->attributes ?> />
</div>
