<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>

<?= $this->render('form/element/input.phtml', ['element' => $element]); ?>
<?php $element->attributes->id .= 0; ?>
<div class="form-group <?= $element->valid ? '' : 'has-error' ?>">
    <label for="<?= $element->attributes->id ?>"><?= $this->translate('PasswordConfirmation') ?></label>
    <input class="form-control" <?= $element->attributes ?> />
</div>
