<?php
/**
 * @var umi\form\FormEntityView $element
 */
?>

<div class="form-group">
    <label for="<?= $element->attributes->id ?>"><?= $element->label ?></label>

    <?php if (!$element->valid) : ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($element->errors as $message) : ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <textarea class="form-control" rows="4" <?= $element->attributes ?> ><?= $element->value ?></textarea>
</div>