<?php
/**
 * @var \umicms\orm\selector\CmsSelector $list
 * @var umicms\project\module\blog\api\object\BlogAuthor $blogAuthor
 */
?>
<?php if ($list->getTotal()) : ?>
    <ol class="list-unstyled">
        <?php foreach ($list as $blogAuthor) : ?>
            <li>
                <?=$this->widget('blog.author.view', ['blogAuthor' => $blogAuthor, 'template' => 'listShortView'])?>
                <?=$this->widget('blog.author.rssList', ['blogAuthor' => $blogAuthor, 'template' => 'rssLink'])?>
            </li>
        <?php endforeach; ?>
    </ol>
<? endif; ?>