<?php if ($authors->getTotal()) : ?>
    <ol class="list-unstyled">
        <?php foreach ($authors as $blogAuthor) : ?>
            <li>
                <?=$this->widget('blog.author.view', ['blogAuthor' => $blogAuthor, 'template' => 'listShortView'])?>
                <?=$this->widget('blog.author.rss', ['blogAuthor' => $blogAuthor, 'template' => 'rssLink'])?>
            </li>
        <?php endforeach; ?>
    </ol>
<? endif; ?>