<?php
/**
 * @var \umicms\orm\selector\CmsSelector $authors
 * @var umicms\project\module\blog\api\object\BlogAuthor $blogAuthor
 */
?>
<?php if ($authors->getTotal()) :?>
    <ul>
        <?php foreach ($authors as $blogAuthor) : ?>
            <li>
                <?=$this->widget('blog.author.view', ['blogAuthor' => $blogAuthor, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>