<?php
/**
 * @var umi\orm\selector\ISelector $posts
 * @var umicms\project\module\blog\api\object\BlogPost $blogPost
 */
?>
<?php if ($posts->getTotal()) :?>

    <ul>
        <?php foreach ($posts as $blogPost) : ?>
            <li>
                <?= $this->widget('blog.post.view', ['blogPost' => $blogPost, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>