<?php
/**
 * @var umicms\orm\selector\CmsSelector $list
 * @var umicms\project\module\blog\api\object\BlogPost $blogPost
 */
?>
<?php if ($list->getTotal()) :?>
    <ul>
        <?php foreach ($list as $blogPost) : ?>
            <li>
                <?= $this->widget('blog.post.view', ['blogPost' => $blogPost, 'template' => 'shortView']); ?>
                <?= $this->widget('blog.post.editPostLink', ['blogPost' => $blogPost, 'template' => 'editPostLink']); ?>
                <?= $this->widget('blog.post.unPublish', ['blogPost' => $blogPost, 'template' => 'unPublishPostForm']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>