<?php
/**
 * @var umicms\project\module\news\api\object\NewsRubric $rubric
 * @var umi\orm\selector\ISelector $rubrics
 */
?>

<?php if ($rubrics->getTotal()) :?>

    <ul>
        <?php foreach ($rubrics as $rubric) : ?>
            <li>
                <?= $this->widget('news.rubric.view', ['guid' => $rubric->guid, 'template' => 'shortView']); ?>
                RSS: <a href="<?= $this->widget('news.rubric.rss', ['rubricGuid' => $rubric->guid]); ?>"><?= $this->widget('news.rubric.rss', ['rubricGuid' => $rubric->guid]); ?></a>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>