<?php
/**
 * @var \umicms\orm\selector\CmsSelector $tags
 * @var umicms\project\module\blog\module\object\BlogTag $tag
 * @var umicms\project\module\blog\module\object\BlogTag $blogTag
 */
?>
<?php foreach ($tags as $blogTag) : ?>

    <?php $tag = $blogTag['tag']; ?>

    <p style="font-size: <?=$blogTag['weight']?>px">
        <a href="<?= $tag->getPageUrl() ?>">
            <?= $tag->displayName; ?>
        </a>
    </p>
<?php endforeach;?>