<?php
/**
 * @var \umicms\orm\selector\CmsSelector $tags
 * @var umicms\project\module\blog\api\object\BlogTag $blogTag
 */
?>
<?php if ($tags->getTotal()) :?>
    <ol class="list-unstyled">
        <?php foreach ($tags as $blogTag) : ?>
            <li>
                <?= $this->widget('blog.tag.view', ['blogTag' => $blogTag, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ol>
<?php endif; ?>