<?php
/**
 * @var \umicms\orm\selector\CmsSelector $list
 * @var umicms\project\module\blog\module\object\BlogTag $blogTag
 */
?>
<?php if ($list->getTotal()) :?>
    <ol class="list-unstyled">
        <?php foreach ($list as $blogTag) : ?>
            <li>
                <?= $this->widget('blog.tag.view', ['blogTag' => $blogTag, 'template' => 'shortView']); ?>
            </li>
        <?php endforeach;?>
    </ol>
<?php endif; ?>