<?php
/**
 * @var umicms\project\module\blog\api\object\BlogPost $blogModerate
 */
?>
<div class="blog-post">
    <h1><?= $blogModerate->displayName ?></h1>
    <p class="blog-post-meta">
        <?php if ($blogModerate->publishTime) : ?>
        <time datetime="<?= $blogModerate->publishTime->format('c')?>">
            <?= $blogModerate->publishTime->format('d.m.Y | H:i')?>
        </time>
        <?php endif; ?>
        <?php if ($blogModerate->author) : ?><?=$this->translate('Автор')?>: <a href="<?=$blogModerate->author->getPageUrl()?>"><?=$blogModerate->author->displayName?></a><?php endif; ?>
        <?=$this->widget('blog.moderate.editPostLink', ['blogModerate' => $blogModerate, 'template' => 'editPostLink'])?>
    </p>

    <?= $blogModerate->announcement ?>

    <a href="<?= $blogModerate->getPageUrl() ?>"><?=$this->translate('Читать далее')?></a>
    <?=$this->widget('blog.moderate.publishModerate', ['blogModerate' => $blogModerate, 'template' => 'publishModerateForm'])?>
    <?=$this->widget('blog.moderate.rejectModerate', ['blogModerate' => $blogModerate, 'template' => 'rejectModerateForm'])?>
</div>