<?php
/**
 * @var umicms\project\module\blog\api\object\BlogPost $blogPost
 */
?>
<div class="blog-post">
    <h1><?= $blogPost->displayName ?></h1>
    <p class="blog-post-meta">
        <?php if ($blogPost->publishTime) : ?>
        <time datetime="<?= $blogPost->publishTime->format('c')?>">
            <?= $blogPost->publishTime->format('d.m.Y | H:i')?>
        </time>
        <?php endif; ?>
        <?php if ($blogPost->author) : ?><?=$this->translate('Автор')?>: <a href="<?=$blogPost->author->getPageUrl()?>"><?=$blogPost->author->displayName?></a><?php endif; ?>
        <?=$this->widget('blog.moderate.editPostLink', ['blogPost' => $blogPost, 'template' => 'editPostLink'])?>
    </p>

    <?= $blogPost->announcement ?>

    <a href="<?= $blogPost->getPageUrl() ?>"><?=$this->translate('Читать далее')?></a>
    <?=$this->widget('blog.moderate.publishModerate', ['blogPost' => $blogPost, 'template' => 'publishModerateForm'])?>
    <?=$this->widget('blog.moderate.rejectModerate', ['blogPost' => $blogPost, 'template' => 'rejectModerateForm'])?>
</div>