<?php
/**
 * @var umi\form\FormEntityView $element
 */

switch($element->type)
{
    case 'fieldset': {
        echo $this->render('form/element/fieldset.phtml', ['element' => $element]);
        break;
    }
    case 'textarea':
    case 'wysiwyg': {
        echo $this->render('form/element/textarea.phtml', ['element' => $element]);
        break;
    }
    case 'select':
    case 'multiSelect': {
        echo $this->render('form/element/select.phtml', ['element' => $element]);
        break;
    }
    case 'checkboxGroup': {
        echo $this->render('form/element/checkboxGroup.phtml', ['element' => $element]);
        break;
    }
    case 'checkbox': {
        echo $this->render('form/element/checkbox.phtml', ['element' => $element]);
        break;
    }
    case 'radio': {
        echo $this->render('form/element/radio.phtml', ['element' => $element]);
        break;
    }
    case 'hidden':
    case 'csrf': {
        echo $this->render('form/element/hidden.phtml', ['element' => $element]);
        break;
    }
    case 'captcha': {
        echo $this->render('form/element/captcha.phtml', ['element' => $element]);
        break;
    }
    case 'passwordWithConfirmation': {
        echo $this->render('form/element/passwordWithConfirmation.phtml', ['element' => $element]);
        break;
    }
    default: {
        switch($element->tag)
        {
            case 'button': {
                echo $this->render('form/element/button.phtml', ['element' => $element]);
                break;
            }
            case 'input': {
                echo $this->render('form/element/input.phtml', ['element' => $element]);
                break;
            }
        }
    }
}

