<?php
/**
 * @var umi\form\FormEntityView $form
 */
?>

<?php if (isset($errors)) : ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($errors as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<form <?= $form->attributes ?> >

    <?php foreach ($form->elements as $element) : ?>
        <?= $this->render('form/element.phtml', ['element' => $element]); ?>
    <?php endforeach; ?>

</form>
