<!DOCTYPE html>
<html lang="en">
<head>
    <?=$this->render('partial/head.phtml', $scope) ?>
</head>

<body>

<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">

        <div class="navbar-collapse collapse">
            <?=$this->widget('structure.menu.auto', ['depth' => 1])?>

            <?php if (count($locales)) : ?>
                <ul class="nav navbar-nav navbar-right">
                    <?php foreach ($locales as $localeId => $localeInfo) : ?>
                        <li class="<?= $localeInfo['current'] ? 'active' : '' ?>">
                            <a href="<?= $localeInfo['url'] ?>"><?= $this->translate($localeId) ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

        </div>

    </div>
</div>

<div class="container">

    <header class="blog-header">
        <?=$this->widget('structure.infoblock.view')?>
    </header>

    <main class="row">

        <article class="col-sm-8 blog-main">

            <?=$contents?>

        </article>

        <aside class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <?=$this->render('partial/sidebar-blog.phtml', $scope) ?>
        </aside>

    </main>

</div>

<footer class="blog-footer">
    <?=$this->widget('structure.infoblock.view', ['template' => 'share'])?>
    <?=$this->widget('structure.infoblock.view', ['template' => 'copyright'])?>
    <p>
        <a href="#"><?=$this->translate('Наверх')?></a>
    </p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/bootstrap/js/docs.min.js"></script>
</body>
</html>