<!DOCTYPE html>
<html lang="en">
<head>
    <?=$this->render('partial/head.phtml', $scope) ?>
</head>

<body>

<div class="blog-masthead">
    <div class="container">

        <?=$this->widget('structure.menu.auto', ['depth' => 1])?>

    </div>
</div>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title"><?=$this->translate('Demo lite twig')?></h1>
        <p class="lead blog-description"><?=$this->translate('Blank-шаблон созданный на Umicms 3')?></p>
    </div>

    <div class="row">

        <div class="col-sm-8 blog-main">

            <?=$contents?>

        </div>

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <?=$this->render('partial/sidebar-news.phtml', $scope) ?>
        </div>

    </div>

</div>

<div class="blog-footer">
    <p>
        <?=$this->translate(
            'Demo lite twig build for {bootstrap} by {umicms}',
            [
                'bootstrap' => '<a href="http://getbootstrap.com">Bootstrap</a>',
                'umicms' => '<a href="http://umi-cms.ru/">umi-cms.ru</a>'
            ]
        )?>.
    </p>
    <p>
        <a href="#"><?=$this->translate('Наверх')?></a>
    </p>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/bootstrap/js/docs.min.js"></script>
</body>
</html>