<!DOCTYPE html>
<html lang="en">
<head>
    <?=$this->render('partial/head.phtml', $scope) ?>
</head>

<body>

<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">

        <div class="navbar-collapse collapse">
            <?=$this->widget('structure.menu.auto', ['depth' => 1])?>

            <?php if (count($locales)) : ?>
                <ul class="nav navbar-nav navbar-right">
                    <?php foreach ($locales as $localeId => $localeInfo) : ?>
                        <li class="<?= $localeInfo['current'] ? 'active' : '' ?>">
                            <a href="<?= $localeInfo['url'] ?>"><?= $this->translate($localeId) ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

        </div>

    </div>
</div>

<div class="container">

    <header class="blog-header">
        <h1 class="blog-title"><?=$this->translate('Demo lite twig')?></h1>
        <p class="lead blog-description"><?=$this->translate('Blank-шаблон созданный на Umicms 3')?></p>
    </header>

    <main class="row">

        <section class="col-sm-8 blog-main">

            <?=$contents?>

        </section>

        <aside class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <?=$this->render('partial/sidebar-news.phtml', $scope) ?>
        </aside>

    </main>

</div>

<footer class="blog-footer">
    <p>
        <?=$this->translate(
            'Demo lite twig build for {bootstrap} by {umicms}',
            [
                'bootstrap' => '<a href="http://getbootstrap.com">Bootstrap</a>',
                'umicms' => '<a href="http://umi-cms.ru/">umi-cms.ru</a>'
            ]
        )?>.
    </p>
    <p>
        <a href="#"><?=$this->translate('Наверх')?></a>
    </p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/bootstrap/js/docs.min.js"></script>
</body>
</html>