<?php
/**
 * @var umicms\project\module\structure\api\object\SystemPage $page
 * @var umi\form\IForm $form
 * @var bool $authenticated
 */
?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->displayName?></h2>
    <?=$page->contents?>

    <?php $errors = isset($errors) ? $errors : null ?>
    <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>

</div>