<?php
/**
 * @var umicms\project\module\news\object\NewsRubric $rubric
 */
?>
<h2>
    <a href="<?= $this->url('rubric', ['url' => ltrim($rubric->getURL(), '/')]); ?>">
        <?= $rubric->h1 ?>
    </a>
</h2>
<?= $this->widget('rubricList', ['parentGuid' => $rubric->guid, 'template' => 'rubric/list']); ?>
<?= $this->widget('rubricNewsList', ['rubricGuids' => [$rubric->guid], 'template' => 'item/list']); ?>