<?php
/**
 * @var string $activationCode
 * @var string $projectUrl
 * @var \umicms\project\module\users\api\object\AuthorizedUser $user
 */

?>

<p><?= $this->translate('Hello')?>, <?= $user->displayName ?></p>

<p><?= $this->translate('In order to complete your registration, visit the following URL')?>: <br/>
    <?= $this->widget('users.registration.activation.link', ['template' => 'link', 'activationCode' => $activationCode]); ?>
</p>

