<?php
/**
 * @var umi\form\FormEntityView $form
 * @var bool $added
 * @var \umicms\project\module\blog\model\object\BlogPost $blogPost
 */
use umicms\project\module\blog\model\object\BlogPost;

?>
<?=$this->render('breadcrumbs.phtml', $scope) ?>
<?php if ($added) : ?>
    <div class="alert alert-success">
        <p class="bg-success text-success"><?=$this->translate('Post has been added.')?></p>
        <p class="bg-success text-success">
            <?php if ($blogPost instanceof BlogPost) : ?>
                <a href="<?=$blogPost->getPageUrl()?>" class="alert-link">
                    <?=$this->translate('ReadMore')?>
                </a>
            <?php endif; ?>
        </p>
    </div>
<?php else : ?>
    <?=$this->render('form/form.phtml', ['form' => $form])?>
<?php endif; ?>