<?php
/**
 * @var umicms\project\module\structure\model\object\SystemPage $page
 * @var umi\form\FormEntityView $form
 * @var bool $authenticated
 */
?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->getHeader()?></h2>
    <?=$page->contents?>

    <?php $errors = isset($errors) ? $errors : null ?>
    <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>

    <h2><?= $this->translate('Change password')?></h2>
    <?= $this->widget('users.profile.password.form', ['template' => 'form']) ?>

</div>