<?php
/**
 * @var umi\orm\selector\ISelector $authors
 * @var umicms\project\module\blog\api\object\BlogAuthor $blogAuthor
 */
?>
<?php if ($authors->getTotal()) :?>
    <ul>
        <?php foreach ($authors as $blogAuthor) : ?>
            <li>
                <?= $this->widget('blog.author.view', ['blogAuthor' => $blogAuthor, 'template' => 'shortView']); ?>
                <?= $this->widget('blog.author.rss', ['blogAuthor' => $blogAuthor, 'template' => 'rssLink']); ?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif; ?>