<?php
/**
 * @var umicms\orm\selector\CmsSelector $list
 * @var \umicms\project\module\forum\model\object\ForumConference $forumConference
 */
?>

<table class="table table-bordered">
    <thead>
    <tr>
        <th><?=$this->translate('Title')?></th>
        <th><?=$this->translate('Themes')?></th>
        <th><?=$this->translate('Messages')?></th>
        <th><?=$this->translate('LastMessage')?></th>
    </tr>
    </thead>
    <tbody>
        <?php if ($list->getTotal()) : ?>
            <?php foreach ($list as $forumConference) : ?>
                <?= $this->widget('forum.conference.view.view', ['forumConference' => $forumConference, 'template' => 'shortView']); ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>