<?php
/**
 * @var umicms\project\module\blog\api\object\BlogPost $page
 */
?>
<div class="blog-post">
    <h1><?=$page->h1?></h1>
    <p class="blog-post-meta">
        <time datetime="<?= $page->publishTime->format('c')?>">
            <?= $page->publishTime->format('d.m.Y | H:i')?>
        </time>
        Автор: <?php if ($page->author) : ?><a href="<?=$page->author->getPageUrl()?>"><?=$page->author->displayName?></a><?php endif ?>
    </p>

    <?= $page->contents ?>

</div>

<h1>Комментарии:</h1>

<?=$this->widget('blog.comment.list', ['blogPost' => $page, 'template' => 'list']); ?>

<?=$this->widget('blog.comment.addComment', ['blogPost' => $page, 'template' => 'addComment'])?>