<?php
/**
 * @var umicms\project\module\blog\api\object\BlogPost $blogDraft
 */
?>
<div class="blog-post">
    <h1><?= $blogDraft->h1 ?></h1>
    <p class="blog-post-meta">
        <time datetime="<?= $blogDraft->publishTime->format('c')?>">
            <?= $blogDraft->publishTime->format('d.m.Y | H:i')?>
        </time>
        Автор: <?php if ($blogDraft->author) : ?><a href="<?=$blogDraft->author->getPageUrl()?>"><?=$blogDraft->author->displayName?></a><?php endif; ?>
        <?=$this->widget('blog.draft.editDraftLink', ['blogDraft' => $blogDraft, 'template' => 'editDraftLink'])?>
    </p>

    <?= $blogDraft->announcement ?>

    <a href="<?= $blogDraft->getPageUrl() ?>">Читать далее</a>
    <?=$this->widget('blog.draft.publishDraft', ['blogDraft' => $blogDraft, 'template' => 'publishDraftForm'])?>
</div>