<?php
use umicms\exception\LibXMLException;

/**
 * @var bool $showTrace
 * @var bool $showStack
 * @var \LibXMLError $libXmlError
 */
?>

<!DOCTYPE HTML>
<html data-foundation>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UMI.CMS</title>
</head>
<body>
    <h1>Ошибка</h1>
    <h2><?= $e->getMessage() ?></h2>

    <?php if ($showTrace): ?>
        <h3>Trace:</h3>
        <pre><?= $e->getTraceAsString() ?></pre>
    <?php endif?>

    <?php if ($showStack): ?>

        <?php $error = $e->getPrevious(); ?>

        <?php if ($error) :?>
            <hr/>
            <h3>Previous exceptions:</h3>
            <ul>
                <?php while ($error) : ?>
                    <li>
                        <h4><?= get_class($error); ?></h4>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre><?= $error->getFile() ?>:<?= $error->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre><?= $error->getMessage(); ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre><?= $error->getTraceAsString() ?></pre>
                            </dd>

                            <?php if ($error instanceof LibXMLException): ?>

                                <dt>Errors:</dt>
                                <dd>
                                        <?php foreach ($error->getErrors() as $libXmlError) : ?>

                                                <?php switch ($libXmlError->level) {
                                                    case LIBXML_ERR_WARNING:
                                                        echo ('<b>Warning</b> :');
                                                        break;
                                                    case LIBXML_ERR_ERROR:
                                                        echo ('<b>Error</b> :');
                                                        break;
                                                    case LIBXML_ERR_FATAL:
                                                        echo ('<b>Fatal error</b> :');
                                                        break;
                                                }
                                                ?>
                                                <?= $libXmlError->message ?>
                                                <?php if ($libXmlError->file): ?>
                                                    in <b><?= $libXmlError->file ?></b> on line <b><?= $libXmlError->line?></b>
                                                <?php endif?>
                                                <br/>
                                        <?php endforeach; ?>
                                </dd>
                            <?php endif?>


                        </dl>
                    </li>
                    <?php
                    $error = $error->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>
    <?php endif?>
</body>
</html>