<?php
/**
 * @var umi\form\IForm $form
 * @var umi\form\element\BaseFormElement $element
 * @var umi\templating\helper\form\FormHelper $formHelper
 */

?>

<?php $formHelper = $this->form(); ?>
<?=$formHelper->openTag($form)?>

    <?php foreach ($form as $element) : ?>
        <p>
        <?=$this->translate($element->getLabel())?>
        <?=$formHelper->formElement($element)?>
        </p>
    <?php endforeach; ?>

    <input value="Отправить" type="submit" />
<?=$formHelper->closeTag()?>