<?php
/**
 * @var umicms\project\module\structure\api\object\SystemPage $page
 * @var umi\form\IForm $form
 * @var bool $success
 */

?>

<div class="blog-post">
    <h2 class="blog-post-title"><?=$page->displayName?></h2>
    <?=$page->contents?>

    <?php if ($success) : ?>

        <div class="alert alert-success">
            <p><?= $this->translate("An email with instructions on how to reset your password was sent to your email") ?>.</p>
        </div>

    <?php else : ?>
        <?php $errors = isset($errors) ? $errors : null ?>
        <?= $this->render('form/form.phtml', ['form' => $form, 'errors' => $errors]) ?>
    <?php endif; ?>

</div>